CREATE TABLE VALIDITY_PERIOD (
    VALIDITY_PERIOD_ID     integer PRIMARY KEY,
    START_DATE             DATE NOT NULL,
    END_DATE               DATE
);

CREATE TABLE PARTY_TYPE_VALUES (
    PARTY_TYPE_CODE VARCHAR(30) PRIMARY KEY,
    DESCRIPTION     VARCHAR(255)
);

CREATE TABLE PARTY_ROLE_TYPE_VALUES (
    PARTY_ROLE_TYPE_CODE VARCHAR(50) PRIMARY KEY,
    DESCRIPTION          VARCHAR(255)
);

CREATE TABLE PARTY_RELATIONSHIP_TYPE_VALUES (
    RELATIONSHIP_TYPE_CODE VARCHAR(50) PRIMARY KEY,
    DESCRIPTION            VARCHAR(255)
);

CREATE TABLE PARTY_LOCATION_TYPE_VALUES (
    PARTY_LOCATION_TYPE_CODE VARCHAR(50) PRIMARY KEY,
    DESCRIPTION              VARCHAR(255)
);

CREATE TABLE LOCATION_TYPE_VALUES (
    LOCATION_TYPE_CODE VARCHAR(50) PRIMARY KEY,
    DESCRIPTION        VARCHAR(255)
);

CREATE TABLE ADDRESS_TYPE_VALUES (
    ADDRESS_TYPE_CODE VARCHAR(50) PRIMARY KEY,
    DESCRIPTION       VARCHAR(255)
);

CREATE TABLE DOCUMENT_TYPE_VALUES (
    DOCUMENT_TYPE_CODE VARCHAR(50) PRIMARY KEY,
    DESCRIPTION        VARCHAR(255)
);

CREATE TABLE ORGANISATION_TYPE_VALUES (
    ORGANISATION_TYPE_CODE VARCHAR(50) PRIMARY KEY,
    DESCRIPTION            VARCHAR(255)
);

CREATE TABLE PARTY (
    PARTY_ID              integer PRIMARY KEY,
    PARTY_NAME            VARCHAR(255),
    PARTY_TYPE_CODE       VARCHAR(30) NOT NULL,
    PARTY_STATUS          VARCHAR(50),
    START_DATE            DATE,
    END_DATE              DATE,
    CONSTRAINT FK_PARTY_TYPE
        FOREIGN KEY (PARTY_TYPE_CODE)
        REFERENCES PARTY_TYPE_VALUES (PARTY_TYPE_CODE)
);

CREATE TABLE PARTY_IDENTIFICATION (
    PARTY_IDENTIFICATION_ID integer PRIMARY KEY,
    PARTY_ID                integer NOT NULL,
    IDENTIFICATION_TYPE     VARCHAR(50),
    IDENTIFIER_VALUE        VARCHAR(100),
    ISSUING_AUTHORITY       VARCHAR(255),
    VALIDITY_PERIOD_ID      integer,
    CONSTRAINT FK_PID_PARTY FOREIGN KEY (PARTY_ID)
        REFERENCES PARTY (PARTY_ID),
    CONSTRAINT FK_PID_PERIOD FOREIGN KEY (VALIDITY_PERIOD_ID)
        REFERENCES VALIDITY_PERIOD (VALIDITY_PERIOD_ID)
);

CREATE TABLE PARTY_ROLE (
    PARTY_ROLE_ID          integer PRIMARY KEY,
    PARTY_ID               integer NOT NULL,
    PARTY_ROLE_NAME        VARCHAR(255),
    PARTY_ROLE_TYPE_CODE   VARCHAR(50),
    VALIDITY_PERIOD_ID     integer,
    CONSTRAINT FK_ROLE_PARTY FOREIGN KEY (PARTY_ID)
        REFERENCES PARTY (PARTY_ID),
    CONSTRAINT FK_ROLE_TYPE FOREIGN KEY (PARTY_ROLE_TYPE_CODE)
        REFERENCES PARTY_ROLE_TYPE_VALUES (PARTY_ROLE_TYPE_CODE),
    CONSTRAINT FK_ROLE_PERIOD FOREIGN KEY (VALIDITY_PERIOD_ID)
        REFERENCES VALIDITY_PERIOD (VALIDITY_PERIOD_ID)
);

CREATE TABLE PARTY_RELATIONSHIP (
    PARTY_RELATIONSHIP_ID  integer PRIMARY KEY,
    FROM_PARTY_ID          integer NOT NULL,
    TO_PARTY_ID            integer NOT NULL,
    RELATIONSHIP_TYPE_CODE VARCHAR(50),
    CONSTRAINT FK_PR_FROM FOREIGN KEY (FROM_PARTY_ID)
        REFERENCES PARTY (PARTY_ID),
    CONSTRAINT FK_PR_TO FOREIGN KEY (TO_PARTY_ID)
        REFERENCES PARTY (PARTY_ID),
    CONSTRAINT FK_PR_TYPE FOREIGN KEY (RELATIONSHIP_TYPE_CODE)
        REFERENCES PARTY_RELATIONSHIP_TYPE_VALUES (RELATIONSHIP_TYPE_CODE)
);
CREATE TABLE PARTY_OBLIGATION_ENTITLEMENT (
    OBLIGATION_ENTITLEMENT_ID integer PRIMARY KEY,
    PARTY_ROLE_ID             integer NOT NULL,
    SUBJECT                   VARCHAR(255),
    TYPE                      VARCHAR(50),
    MODALITY                  VARCHAR(50),
    DEFINITION                VARCHAR(500),
    CONSTRAINT FK_POE_ROLE FOREIGN KEY (PARTY_ROLE_ID)
        REFERENCES PARTY_ROLE (PARTY_ROLE_ID)
);
CREATE TABLE PERSON (
    PERSON_ID        integer PRIMARY KEY,
    PARTY_ID         integer UNIQUE NOT NULL,
    BIRTH_DATE       DATE,
    NATIONALITY      VARCHAR(100),
    RESIDENCY_STATUS VARCHAR(50),
    CIVIL_STATUS     VARCHAR(50),
    CONSTRAINT FK_PERSON_PARTY FOREIGN KEY (PARTY_ID)
        REFERENCES PARTY (PARTY_ID)
);
CREATE TABLE ORGANISATION (
    ORGANISATION_ID        integer PRIMARY KEY,
    PARTY_ID               integer UNIQUE NOT NULL,
    ORGANISATION_NAME      VARCHAR(255),
    ORGANISATION_TYPE_CODE VARCHAR(50),
    INCORPORATION_DATE     DATE,
    CONSTRAINT FK_ORG_PARTY FOREIGN KEY (PARTY_ID)
        REFERENCES PARTY (PARTY_ID),
    CONSTRAINT FK_ORG_TYPE FOREIGN KEY (ORGANISATION_TYPE_CODE)
        REFERENCES ORGANISATION_TYPE_VALUES (ORGANISATION_TYPE_CODE)
);
CREATE TABLE LOCATION (
    LOCATION_ID        integer PRIMARY KEY,
    LOCATION_NAME      VARCHAR(255),
    LOCATION_TYPE_CODE VARCHAR(50),
    LOCATION_STATUS    VARCHAR(50),
    TIME_ZONE          VARCHAR(50),
    CAPACITY           VARCHAR(50),
    CONSTRAINT FK_LOC_TYPE FOREIGN KEY (LOCATION_TYPE_CODE)
        REFERENCES LOCATION_TYPE_VALUES (LOCATION_TYPE_CODE)
);
CREATE TABLE ADDRESS (
    ADDRESS_ID        integer PRIMARY KEY,
    LOCATION_ID       integer NOT NULL,
    ADDRESS_TYPE_CODE VARCHAR(50),
    STREET_NAME       VARCHAR(255),
    BUILDING_NUMBER   VARCHAR(50),
    CITY              VARCHAR(100),
    POSTAL_CODE       VARCHAR(20),
    COUNTRY           VARCHAR(100),
    CONSTRAINT FK_ADDR_LOC FOREIGN KEY (LOCATION_ID)
        REFERENCES LOCATION (LOCATION_ID),
    CONSTRAINT FK_ADDR_TYPE FOREIGN KEY (ADDRESS_TYPE_CODE)
        REFERENCES ADDRESS_TYPE_VALUES (ADDRESS_TYPE_CODE)
);
CREATE TABLE PARTY_LOCATION (
    PARTY_LOCATION_ID integer PRIMARY KEY,
    PARTY_ID          integer NOT NULL,
    LOCATION_ID       integer NOT NULL,
    PARTY_LOCATION_TYPE_CODE VARCHAR(50),
    CONSTRAINT FK_PL_PARTY FOREIGN KEY (PARTY_ID)
        REFERENCES PARTY (PARTY_ID),
    CONSTRAINT FK_PL_LOC FOREIGN KEY (LOCATION_ID)
        REFERENCES LOCATION (LOCATION_ID),
    CONSTRAINT FK_PL_TYPE FOREIGN KEY (PARTY_LOCATION_TYPE_CODE)
        REFERENCES PARTY_LOCATION_TYPE_VALUES (PARTY_LOCATION_TYPE_CODE)
);
CREATE TABLE DOCUMENT (
    DOCUMENT_ID        integer PRIMARY KEY,
    DOCUMENT_TYPE_CODE VARCHAR(50),
    DOCUMENT_STATUS    VARCHAR(50),
    DOCUMENT_DATE      DATE,
    DOCUMENT_PURPOSE   VARCHAR(255),
    DESCRIPTION        VARCHAR(500),
    CONSTRAINT FK_DOC_TYPE FOREIGN KEY (DOCUMENT_TYPE_CODE)
        REFERENCES DOCUMENT_TYPE_VALUES (DOCUMENT_TYPE_CODE)
);
CREATE TABLE PARTY_DOCUMENT (
    PARTY_DOCUMENT_ID integer PRIMARY KEY,
    PARTY_ID          integer NOT NULL,
    DOCUMENT_ID       integer NOT NULL,
    CONSTRAINT FK_PD_PARTY FOREIGN KEY (PARTY_ID)
        REFERENCES PARTY (PARTY_ID),
    CONSTRAINT FK_PD_DOC FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENT (DOCUMENT_ID)
);
CREATE TABLE DOCUMENT_RELATIONSHIP (
    DOCUMENT_RELATIONSHIP_ID integer PRIMARY KEY,
    FROM_DOCUMENT_ID         integer,
    TO_DOCUMENT_ID           integer,
    RELATIONSHIP_TYPE        VARCHAR(50),
    CONSTRAINT FK_DR_FROM FOREIGN KEY (FROM_DOCUMENT_ID)
        REFERENCES DOCUMENT (DOCUMENT_ID),
    CONSTRAINT FK_DR_TO FOREIGN KEY (TO_DOCUMENT_ID)
        REFERENCES DOCUMENT (DOCUMENT_ID)
);

